#!/usr/bin/env bash

set -e

go install ./...
go test ./...

for test in tests/*; do
	echo "Running $test"
	DIR=`mktemp -d -t tvm-tests-XXXXXXX` || (echo "Failed to create tmp directory"; exit 1)
	javac -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
	diff <(tvm ${DIR}/*) $test/out
done
