#!/usr/bin/env bash

set -e

: ${RT:="/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/lib/rt.jar"}

go install ./...

test=tests/$1;
NAME=`cut -d'/' -f2 <<<"$test"`
DIR=`mktemp -d -t tvm-tests-XXXXXXX` || (echo "Failed to create tmp directory"; exit 1)
javac -bootclasspath stdlib:$RT -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
find stdlib -type f -name '*.java' | xargs javac -d $DIR || (echo "Failed to compile"; exit 1)
find stdlib -type f -name '*.class' | xargs -I{} -n1 cp {} $DIR/
find $DIR -type f
find $DIR -type f | xargs go run cmd/visual-tvm/main.go
